
export type CurrenciesFlagType = {code : string, flag: string, name: string, rate?: number};

export const currenciesFlag : CurrenciesFlagType[] =
[
    { "code": "AED", "flag": "🇦🇪", "name": "United Arab Emirates Dirham" },
    { "code": "AFN", "flag": "🇦🇫", "name": "Afghan Afghani" },
    { "code": "ALL", "flag": "🇦🇱", "name": "Albanian Lek" },
    { "code": "AMD", "flag": "🇦🇲", "name": "Armenian Dram" },
    { "code": "ANG", "flag": "🇨🇼", "name": "Netherlands Antillean Guilder" },
    { "code": "AOA", "flag": "🇦🇴", "name": "Angolan Kwanza" },
    { "code": "ARS", "flag": "🇦🇷", "name": "Argentine Peso" },
    { "code": "AUD", "flag": "🇦🇺", "name": "Australian Dollar" },
    { "code": "AWG", "flag": "🇦🇼", "name": "Aruban Florin" },
    { "code": "AZN", "flag": "🇦🇿", "name": "Azerbaijani Manat" },
    { "code": "BAM", "flag": "🇧🇦", "name": "Bosnia-Herzegovina Convertible Mark" },
    { "code": "BBD", "flag": "🇧🇧", "name": "Barbadian Dollar" },
    { "code": "BDT", "flag": "🇧🇩", "name": "Bangladeshi Taka" },
    { "code": "BGN", "flag": "🇧🇬", "name": "Bulgarian Lev" },
    { "code": "BHD", "flag": "🇧🇭", "name": "Bahraini Dinar" },
    { "code": "BIF", "flag": "🇧🇮", "name": "Burundian Franc" },
    { "code": "BMD", "flag": "🇧🇲", "name": "Bermudian Dollar" },
    { "code": "BND", "flag": "🇧🇳", "name": "Brunei Dollar" },
    { "code": "BOB", "flag": "🇧🇴", "name": "Bolivian Boliviano" },
    { "code": "BRL", "flag": "🇧🇷", "name": "Brazilian Real" },
    { "code": "BSD", "flag": "🇧🇸", "name": "Bahamian Dollar" },
    { "code": "BTC", "flag": "🌐", "name": "Bitcoin" },
    { "code": "BTN", "flag": "🇧🇹", "name": "Bhutanese Ngultrum" },
    { "code": "BWP", "flag": "🇧🇼", "name": "Botswanan Pula" },
    { "code": "BYN", "flag": "🇧🇾", "name": "Belarusian Ruble" },
    { "code": "BYR", "flag": "🇧🇾", "name": "Belarusian Ruble (2000-2016)" },
    { "code": "BZD", "flag": "🇧🇿", "name": "Belize Dollar" },
    { "code": "CAD", "flag": "🇨🇦", "name": "Canadian Dollar" },
    { "code": "CDF", "flag": "🇨🇩", "name": "Congolese Franc" },
    { "code": "CHF", "flag": "🇨🇭", "name": "Swiss Franc" },
    { "code": "CLP", "flag": "🇨🇱", "name": "Chilean Peso" },
    { "code": "CNH", "flag": "🇨🇳", "name": "Chinese Yuan (Offshore)" },
    { "code": "CNY", "flag": "🇨🇳", "name": "Chinese Yuan" },
    { "code": "COP", "flag": "🇨🇴", "name": "Colombian Peso" },
    { "code": "CRC", "flag": "🇨🇷", "name": "Costa Rican Colón" },
    { "code": "CUC", "flag": "🇨🇺", "name": "Cuban Convertible Peso" },
    { "code": "CUP", "flag": "🇨🇺", "name": "Cuban Peso" },
    { "code": "CVE", "flag": "🇨🇻", "name": "Cape Verdean Escudo" },
    { "code": "CZK", "flag": "🇨🇿", "name": "Czech Republic Koruna" },
    { "code": "DJF", "flag": "🇩🇯", "name": "Djiboutian Franc" },
    { "code": "DKK", "flag": "🇩🇰", "name": "Danish Krone" },
    { "code": "DOP", "flag": "🇩🇴", "name": "Dominican Peso" },
    { "code": "DZD", "flag": "🇩🇿", "name": "Algerian Dinar" },
    { "code": "EEK", "flag": "🇪🇪", "name": "Estonian Kroon" },
    { "code": "EGP", "flag": "🇪🇬", "name": "Egyptian Pound" },
    { "code": "ERN", "flag": "🇪🇷", "name": "Eritrean Nakfa" },
    { "code": "ETB", "flag": "🇪🇹", "name": "Ethiopian Birr" },
    { "code": "EUR", "flag": "🇪🇺", "name": "Euro" },
    { "code": "FJD", "flag": "🇫🇯", "name": "Fijian Dollar" },
    { "code": "FKP", "flag": "🇫🇰", "name": "Falkland Islands Pound" },
    { "code": "GBP", "flag": "🇬🇧", "name": "British Pound Sterling" },
    { "code": "GEL", "flag": "🇬🇪", "name": "Georgian Lari" },
    { "code": "GGP", "flag": "🇬🇬", "name": "Guernsey Pound" },
    { "code": "GHS", "flag": "🇬🇭", "name": "Ghanaian Cedi" },
    { "code": "GIP", "flag": "🇬🇮", "name": "Gibraltar Pound" },
    { "code": "GMD", "flag": "🇬🇲", "name": "Gambian Dalasi" },
    { "code": "GNF", "flag": "🇬🇳", "name": "Guinean Franc" },
    { "code": "GTQ", "flag": "🇬🇹", "name": "Guatemalan Quetzal" },
    { "code": "GYD", "flag": "🇬🇾", "name": "Guyanaese Dollar" },
    { "code": "HKD", "flag": "🇭🇰", "name": "Hong Kong Dollar" },
    { "code": "HNL", "flag": "🇭🇳", "name": "Honduran Lempira" },
    { "code": "HRK", "flag": "🇭🇷", "name": "Croatian Kuna" },
    { "code": "HTG", "flag": "🇭🇹", "name": "Haitian Gourde" },
    { "code": "HUF", "flag": "🇭🇺", "name": "Hungarian Forint" },
    { "code": "IDR", "flag": "🇮🇩", "name": "Indonesian Rupiah" },
    { "code": "ILS", "flag": "🇮🇱", "name": "Israeli New Sheqel" },
    { "code": "IMP", "flag": "🇮🇲", "name": "Manx pound" },
    { "code": "INR", "flag": "🇮🇳", "name": "Indian Rupee" },
    { "code": "IQD", "flag": "🇮🇶", "name": "Iraqi Dinar" },
    { "code": "IRR", "flag": "🇮🇷", "name": "Iranian Rial" },
    { "code": "ISK", "flag": "🇮🇸", "name": "Icelandic Króna" },
    { "code": "JEP", "flag": "🇯🇪", "name": "Jersey Pound" },
    { "code": "JMD", "flag": "🇯🇲", "name": "Jamaican Dollar" },
    { "code": "JOD", "flag": "🇯🇴", "name": "Jordanian Dinar" },
    { "code": "JPY", "flag": "🇯🇵", "name": "Japanese Yen" },
    { "code": "KES", "flag": "🇰🇪", "name": "Kenyan Shilling" },
    { "code": "KGS", "flag": "🇰🇬", "name": "Kyrgystani Som" },
    { "code": "KHR", "flag": "🇰🇭", "name": "Cambodian Riel" },
    { "code": "KMF", "flag": "🇰🇲", "name": "Comorian Franc" },
    { "code": "KPW", "flag": "🇰🇵", "name": "North Korean Won" },
    { "code": "KRW", "flag": "🇰🇷", "name": "South Korean Won" },
    { "code": "KWD", "flag": "🇰🇼", "name": "Kuwaiti Dinar" },
    { "code": "KYD", "flag": "🇰🇾", "name": "Cayman Islands Dollar" },
    { "code": "KZT", "flag": "🇰🇿", "name": "Kazakhstani Tenge" },
    { "code": "LAK", "flag": "🇱🇦", "name": "Laotian Kip" },
    { "code": "LBP", "flag": "🇱🇧", "name": "Lebanese Pound" },
    { "code": "LKR", "flag": "🇱🇰", "name": "Sri Lankan Rupee" },
    { "code": "LRD", "flag": "🇱🇷", "name": "Liberian Dollar" },
    { "code": "LSL", "flag": "🇱🇸", "name": "Lesotho Loti" },
    { "code": "LTL", "flag": "🇱🇹", "name": "Lithuanian Litas" },
    { "code": "LVL", "flag": "🇱🇻", "name": "Latvian Lats" },
    { "code": "LYD", "flag": "🇱🇾", "name": "Libyan Dinar" },
    { "code": "MAD", "flag": "🇲🇦", "name": "Moroccan Dirham" },
    { "code": "MDL", "flag": "🇲🇩", "name": "Moldovan Leu" },
    { "code": "MGA", "flag": "🇲🇬", "name": "Malagasy Ariary" },
    { "code": "MKD", "flag": "🇲🇰", "name": "Macedonian Denar" },
    { "code": "MMK", "flag": "🇲🇲", "name": "Myanma Kyat" },
    { "code": "MNT", "flag": "🇲🇳", "name": "Mongolian Tugrik" },
    { "code": "MOP", "flag": "🇲🇴", "name": "Macanese Pataca" },
    { "code": "MRU", "flag": "🇲🇷", "name": "Mauritanian Ouguiya" },
    { "code": "MUR", "flag": "🇲🇺", "name": "Mauritian Rupee" },
    { "code": "MVR", "flag": "🇲🇻", "name": "Maldivian Rufiyaa" },
    { "code": "MWK", "flag": "🇲🇼", "name": "Malawian Kwacha" },
    { "code": "MXN", "flag": "🇲🇽", "name": "Mexican Peso" },
    { "code": "MYR", "flag": "🇲🇾", "name": "Malaysian Ringgit" },
    { "code": "MZN", "flag": "🇲🇿", "name": "Mozambican Metical" },
    { "code": "NAD", "flag": "🇳🇦", "name": "Namibian Dollar" },
    { "code": "NGN", "flag": "🇳🇬", "name": "Nigerian Naira" },
    { "code": "NIO", "flag": "🇳🇮", "name": "Nicaraguan Córdoba" },
    { "code": "NOK", "flag": "🇳🇴", "name": "Norwegian Krone" },
    { "code": "NPR", "flag": "🇳🇵", "name": "Nepalese Rupee" },
    { "code": "NTD", "flag": "🇹🇼", "name": "New Taiwan Dollar" },
    { "code": "NZD", "flag": "🇳🇿", "name": "New Zealand Dollar" },
    { "code": "OMR", "flag": "🇴🇲", "name": "Omani Rial" },
    { "code": "PAB", "flag": "🇵🇦", "name": "Panamanian Balboa" },
    { "code": "PEN", "flag": "🇵🇪", "name": "Peruvian Nuevo Sol" },
    { "code": "PGK", "flag": "🇵🇬", "name": "Papua New Guinean Kina" },
    { "code": "PHP", "flag": "🇵🇭", "name": "Philippine Peso" },
    { "code": "PKR", "flag": "🇵🇰", "name": "Pakistani Rupee" },
    { "code": "PLN", "flag": "🇵🇱", "name": "Polish Zloty" },
    { "code": "PYG", "flag": "🇵🇾", "name": "Paraguayan Guarani" },
    { "code": "QAR", "flag": "🇶🇦", "name": "Qatari Rial" },
    { "code": "RON", "flag": "🇷🇴", "name": "Romanian Leu" },
    { "code": "RSD", "flag": "🇷🇸", "name": "Serbian Dinar" },
    { "code": "RUB", "flag": "🇷🇺", "name": "Russian Ruble" },
    { "code": "RWF", "flag": "🇷🇼", "name": "Rwandan Franc" },
    { "code": "SAR", "flag": "🇸🇦", "name": "Saudi Riyal" },
    { "code": "SBD", "flag": "🇸🇧", "name": "Solomon Islands Dollar" },
    { "code": "SCR", "flag": "🇸🇨", "name": "Seychellois Rupee" },
    { "code": "SDG", "flag": "🇸🇩", "name": "Sudanese Pound" },
    { "code": "SEK", "flag": "🇸🇪", "name": "Swedish Krona" },
    { "code": "SGD", "flag": "🇸🇬", "name": "Singapore Dollar" },
    { "code": "SHP", "flag": "🇸🇭", "name": "Saint Helena Pound" },
    { "code": "SKK", "flag": "🇸🇰", "name": "Slovak Koruna" },
    { "code": "SLE", "flag": "🇸🇱", "name": "Sierra Leonean Leone" },
    { "code": "SLL", "flag": "🇸🇱", "name": "Sierra Leonean Leone (1964—2022)" },
    { "code": "SOS", "flag": "🇸🇴", "name": "Somali Shilling" },
    { "code": "SPL", "flag": "🇸🇭", "name": "Seborga Luigino" },
    { "code": "SRD", "flag": "🇸🇷", "name": "Surinamese Dollar" },
    { "code": "STN", "flag": "🇸🇹", "name": "São Tomé and Príncipe Dobra" },
    { "code": "SVC", "flag": "🇸🇻", "name": "Salvadoran Colón" },
    { "code": "SYP", "flag": "🇸🇾", "name": "Syrian Pound" },
    { "code": "SZL", "flag": "🇸🇿", "name": "Swazi Lilangeni" },
    { "code": "THB", "flag": "🇹🇭", "name": "Thai Baht" },
    { "code": "TJS", "flag": "🇹🇯", "name": "Tajikistani Somoni" },
    { "code": "TMT", "flag": "🇹🇲", "name": "Turkmenistani Manat" },
    { "code": "TND", "flag": "🇹🇳", "name": "Tunisian Dinar" },
    { "code": "TOP", "flag": "🇹🇴", "name": "Tongan Paʻanga" },
    { "code": "TRY", "flag": "🇹🇷", "name": "Turkish Lira" },
    { "code": "TTD", "flag": "🇹🇹", "name": "Trinidad and Tobago Dollar" },
    { "code": "TVD", "flag": "🇹🇻", "name": "Tuvaluan Dollar" },
    { "code": "TWD", "flag": "🇹🇼", "name": "New Taiwan Dollar" },
    { "code": "TZS", "flag": "🇹🇿", "name": "Tanzanian Shilling" },
    { "code": "UAH", "flag": "🇺🇦", "name": "Ukrainian Hryvnia" },
    { "code": "UGX", "flag": "🇺🇬", "name": "Ugandan Shilling" },
    { "code": "USD", "flag": "🇺🇸", "name": "United States Dollar" },
    { "code": "UYU", "flag": "🇺🇾", "name": "Uruguayan Peso" },
    { "code": "UZS", "flag": "🇺🇿", "name": "Uzbekistan Som" },
    { "code": "VED", "flag": "🇻🇪", "name": "Venezuelan Bolívar Digital" },
    { "code": "VEF", "flag": "🇻🇪", "name": "Venezuelan Bolívar (2008–2018)" },
    { "code": "VES", "flag": "🇻🇪", "name": "Venezuelan Bolívar" },
    { "code": "VND", "flag": "🇻🇳", "name": "Vietnamese Dong" },
    { "code": "VUV", "flag": "🇻🇺", "name": "Vanuatu Vatu" },
    { "code": "WST", "flag": "🇼🇸", "name": "Samoan Tala" },
    { "code": "XAF", "flag": "🇨🇲", "name": "CFA Franc BEAC" },
    { "code": "XCD", "flag": "🇦🇬", "name": "East Caribbean Dollar" },
    { "code": "XDR", "flag": "🌐", "name": "Special Drawing Rights" },
    { "code": "XOF", "flag": "🇧🇯", "name": "CFA Franc BCEAO" },
    { "code": "XPF", "flag": "🇵🇫", "name": "CFP Franc" },
    { "code": "YER", "flag": "🇾🇪", "name": "Yemeni Rial" },
    { "code": "ZAR", "flag": "🇿🇦", "name": "South African Rand" },
    { "code": "ZMW", "flag": "🇿🇲", "name": "Zambian Kwacha" },
    { "code": "ZWD", "flag": "🇿🇼", "name": "Zimbabwean Dollar (1980–2008)" },
    { "code": "ZWL", "flag": "🇿🇼", "name": "Zimbabwean Dollar (2009)" }
]
